### ISSUE TITLE
Diagrama de secuencias_Abigail coronelsantiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo_judith#4]
[DIAGRAMA.DE.SECUENCIA_INGENERIA.DE.SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo_judith/files/10205590/DIAGRAMA.DE.SECUENCIA_INGENERIA.DE.SOFTWARE.pdf)

**Comment by josealfredo79** [comment]
Calificacion 50

**Comment by josealfredo79** [comment]
Bien hecho y revisado
